
/**
 * Generated by CreatorEngine
 */

import { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets } from "babylonjs-editor-tools";
import * as scripts_led from "./scripts/led";
import * as scripts_box from "./scripts/box";

export const scriptsMap = {
    "scripts/led.ts": scripts_led,
	"scripts/box.ts": scripts_box
};

export { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets };
